# Generated by Django 3.2.6 on 2021-08-04 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xpress', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='excert',
            new_name='excerpt',
        ),
    ]
